# Sources
tap 'buo/cask-upgrade'

# Utilities
brew 'mas', retry: 5
brew 'git', retry: 5
brew 'tailscale', retry: 5
brew 'speedtest-cli', retry: 5
brew 'mackup', retry: 5
brew 'ffmpeg', retry: 5
brew 'sevenzip', retry: 5

# Apps from "Web"
cask 'proton-drive', retry: 5
cask 'warp', retry: 5
cask 'alfred', retry: 5
cask 'firefox', retry: 5
cask 'chromium', retry: 5, args: { no_quarantine: true }
cask 'visual-studio-code', retry: 5
cask 'vlc', retry: 5
cask 'crossover', retry: 5
cask 'beeper', retry: 5
cask 'protonvpn', retry: 5
cask 'cryptomator', retry: 5
cask 'appcleaner', retry: 5
cask 'steam', retry: 5
cask 'spotify', retry: 5
cask 'little-snitch', retry: 5
cask 'keepingyouawake', retry: 5
cask 'utm', retry: 5
cask 'shottr', retry: 5
cask 'hiddenbar', retry: 5
cask 'onyx', retry: 5
cask 'daisydisk', retry: 5
cask 'handbrake', retry: 5
cask 'affinity-photo', retry: 5
cask 'affinity-designer', retry: 5
cask 'affinity-publisher', retry: 5
# Apps for Work
cask 'microsoft-office', retry: 5
cask 'cisco-jabber', retry: 5
cask 'webex', retry: 5
cask 'citrix-workspace', retry: 5

# Apps from "App Store"
mas 'Logic Pro', id: 634148309
mas 'Pixelmator Pro', id: 1289583905
mas 'Vivid', id: 6443470555
mas 'Dropover', id: 1355679052