# Sources
tap 'traktuner/traktuner'

# Utilities
brew 'mas'
brew 'git'
brew 'mackup'
brew 'tailscale'

# Browsers
cask 'firefox'
cask 'eloston-chromium', args: { no_quarantine: true }
cask 'warp'

# Privacy & Security
cask 'cryptomator'
cask 'little-snitch'
cask 'microsoft-defender'
cask 'cleanmymac'

# Proton Suite
cask 'proton-drive'
cask 'proton-mail'
cask 'proton-pass'
cask 'protonvpn'
cask 'standard-notes'

# Communication & Collaboration
cask 'beeper'
cask 'cisco-jabber'
cask 'citrix-workspace'
cask 'microsoft-teams'
cask 'webex'

# Productivity
cask 'warp'
cask 'keepingyouawake'
cask 'shottr'
cask 'synology-drive'
cask 'visual-studio-code'
cask 'network-share-mounter'
cask 'libreoffice'

# Media & Creativity
cask 'affinity-designer'
cask 'affinity-photo'
cask 'affinity-publisher'
cask 'darktable', args: { no_quarantine: true }
cask 'topaz-video-ai'
cask 'handbrake'
cask 'vlc'

# Backup & Maintenance
cask 'appcleaner'
cask 'bartender'
cask 'betterzip'
cask 'daisydisk'
cask 'crashplan'

# Emulation & Gaming
cask 'utm'
cask 'xemu', args: { no_quarantine: true }
cask 'crossover'
cask 'steam'

# App Store
# Core Apps
mas 'Logic Pro', id: 634148309
mas 'Pixelmator Pro', id: 1289583905
mas 'Vivid', id: 6443470555
mas 'CEWE Fotoservice', id: 1446275768
mas 'HP Smart', id: 1474276998
mas 'Speedtest', id: 1153157709

# Extensions
mas '1Blocker', id: 1365531024
mas 'Noir', id: 1592917505
mas 'Proton Pass for Safari', id: 6502835663
mas 'StopTheMadness Pro', id: 6471380298
mas 'Wayback Machine', id: 1472432422