### CrashPlan Deployment Configuration
### taken from https://support.code42.com/Administrator/Cloud/Planning_and_installer/Manage_app_installations_in_your_Code42_environment/Deployment_script_and_command_reference

CP_SILENT=true